version: "3"

services:
  server:
    restart: on-failure
    build: .
    command: "poetry run uvicorn --host 0.0.0.0 --port 8000 --loop asyncio --log-config app/api/v1/logging.json app.asgi:app"
    env_file: ".env"
    ports:
      - "8000:8000"
