class Parameters:
    MIN_PLAYERS = 2
    MAX_PLAYERS = 5

    START_DELAY = 1
    START_BONUS_ROUND_AMOUNT = 65

    DEFAULT_PLAYER_BALANCE = 15000
    START_BONUS = 2000
    START_REWARD = 1000
    AUCTION_MINIMUM_BET = 100
    DEFAULT_PRISON_ESCAPE_COST = 500
    DEFAULT_CASINO_BET = 1000

    DEFAULT_MAP_PATH = "app/assets/maps/default_map.json"
